sudo: required

tags: true

services:
- docker

script:
- export REPO=crowdfire/gohaqd
- export TAG=${TRAVIS_TAG:=latest}
- docker build -t $REPO:$TAG .

after_success:
- test $TRAVIS_PULL_REQUEST = "false" -a $TRAVIS_BRANCH = "master" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $REPO

