sudo: required

tags: true

services:
- docker

script:
- export REPO=crowdfire/gohaqd
- export TAG=${TRAVIS_TAG:=latest}
- docker build -t $REPO:$TAG .

after_success:
- '[[ $TRAVIS_PULL_REQUEST = "false" && ( $TRAVIS_BRANCH = "master" || $TRAVIS_BRANCH = "$TRAVIS_TAG" ) ]] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $REPO'

